### ISSUE TITLE
why is getting a redirect url 404?

### ISSUE THREAD

**Issue by serene-ding** [manishkatyan/strapi-stripe#104]
![image](https://github.com/manishkatyan/strapi-stripe/assets/77049532/074af747-6176-4b82-8e22-a97118603fc2)
i have configured the product id

**Comment by maximehamou** [comment]
> ![image](https://private-user-images.githubusercontent.com/77049532/265579006-074af747-6176-4b82-8e22-a97118603fc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MzIwMjEsIm5iZiI6MTcxOTkzMTcyMSwicGF0aCI6Ii83NzA0OTUzMi8yNjU1NzkwMDYtMDc0YWY3NDctNjE3Ni00YjgyLThlMjItYTk3MTE4NjAzZmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDE0NDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNmU5M2NhY2EyM2UyMjA1NjQ5YmViMmU1ZDllZDQ4Y2JhZDEwYjRjNmM4NzllMzIyNjI5N2UzMTNlMTY2NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ej6Ml_JjLdsHHjPV1VJ2iTWFfqVOkuAQc_XcQxpxdZo)

Hello @serene-ding, I have the same issue, how did you resolved it? Thanks!

**Comment by dkhan99** [comment]
@maximehamou @serene-ding 
After running the package in my local debugger I found out that Payment Success Page URL and Payment Cancel Page URL need to start with `https://` or `http://` otherwise they fail a stripe validation and return a 404 error.

After updating it in my Strapi Admin Dashboard it worked!
