### ISSUE TITLE
Strapi v4.14.5 Error 403

### ISSUE THREAD

**Issue by dev2studio** [manishkatyan/strapi-stripe#106]
GET http://localhost:1337/strapi-stripe/getSettings
PUT http://localhost:1337/strapi-stripe/updateSettings

{
    "status": 403,
    "name": "ForbiddenError",
    "message": "Forbidden",
    "details": {}
}

**Comment by Amaan-Shaah** [comment]
Hi , I have the same error can you help me out please?

**Comment by Amaan-Shaah** [comment]
> GET http://localhost:1337/strapi-stripe/getSettings PUT http://localhost:1337/strapi-stripe/updateSettings
> 
> { "status": 403, "name": "ForbiddenError", "message": "Forbidden", "details": {} }

Hi , please check the Tokens in Strapi env in root folder if you have added the tokens.

**Comment by dev2studio** [comment]
yes, its my problem, need add .env token veriebled
