### ISSUE TITLE
403 Forbidden Error while Setting up configuration.

### ISSUE THREAD

**Issue by Amaan-Shaah** [manishkatyan/strapi-stripe#107]
![image](https://github.com/manishkatyan/strapi-stripe/assets/121847858/5b9222f0-a61b-4b35-85ca-b658bf6b438c)
 

Hi , i am using stripe for strapi  and i have not been able to setup my stripe configuration, whenever i check the network logs, i can see that getSettings & updateSettings always return 403, could you help please?

Node version-v18.16.0
npm version -9.5.1

strapi-v4.11.5

**Comment by MGolob** [comment]
You need to create an strapi api token in the settings and provide it in the env file.

**Comment by Amaan-Shaah** [comment]
> You need to create an strapi api token in the settings and provide it in the env file.

Thanks, my token expiration date was not unlimited!

Much appreciate the help!
