### ISSUE TITLE
Recurring payment (subscription)

### ISSUE THREAD

**Issue by mark134340** [manishkatyan/strapi-stripe#14]
Do you have any plans to add this?

**Comment by nishekh-e-r** [comment]
Hi @mark134340
Check the new version of the plugin in two weeks. We are going to add recurring payments.

**Comment by yuriy** [comment]
Hi @nishekh-e-r
Is the recurring payment feature still in progress?
Do you have a deadline for this one?

**Comment by nishekh-e-r** [comment]
Hi @yuriy 
The recurring payment is still in the development phase, You can expect the updated version of this plugin by 20/07/2022.
![subsciption_table](https://user-images.githubusercontent.com/87962465/172308854-0fabb7da-ff5a-49cf-91c3-40b5e0fdca88.png)
![subscription_create](https://user-images.githubusercontent.com/87962465/172308900-31cfe29f-4929-405d-8b68-a00df04c7c6c.png)

**Comment by yuriy** [comment]
@nishekh-e-r nice 👍 
One question, will there be a possibility to make recurring payments each month with different amounts depending on the invoice? (like payments for the service, the price is different each month)

**Comment by nishekh-e-r** [comment]
@yuriy  we have implemented a Recurring (subscription) feature, You install the latest plugin from  [here](https://www.npmjs.com/package/strapi-stripe)

**Comment by yuriy** [comment]
@nishekh-e-r  great, thanks!
