### ISSUE TITLE
PLN currency is missing in the currency dropdown

### ISSUE THREAD

**Issue by Oskinavara** [manishkatyan/strapi-stripe#18]
As stated in the title, PLN (złoty) currency doesn't exist in a dropdown, which make using this plugin for Polish e-commerces impossible. Is there anyway to go around this issue?

**Comment by nishekh-e-r** [comment]
Hi @Oskinavara 
We have added PLN(złoty) currency in the dropdown, you can download the recent version of our plugin [here](https://www.npmjs.com/package/strapi-stripe).
