### ISSUE TITLE
Payment updates

### ISSUE THREAD

**Issue by Puvvl** [manishkatyan/strapi-stripe#28]
Hey! I faced with issue when I try to update product or subscription it doesn't update on stripe side. How should I properly update a product to update it in the stripe?
Also, non-required fields return an errors:
- stripePlanId: return error `This value is too low` for one-time Payment Type (by default it not  filled field)
![1](https://user-images.githubusercontent.com/17503326/175512671-fcafcbc5-d6f4-4933-9606-eaa1da09b500.png)

- stripePriceId the same error for subscription Payment Type (by default it not filled field)
![2](https://user-images.githubusercontent.com/17503326/175512891-641b4f31-dc72-402b-922e-26be696fa0c4.png)

**Comment by nishekh-e-r** [comment]
@Puvvl please use the payment plugin dashboard to update your Product or subscriptions.

You can reference below images:

![strapi-stripe](https://user-images.githubusercontent.com/87962465/175908533-29cc44d3-7dab-427a-866f-714a6e50aaaa.png)
![strapi-stripe-edit](https://user-images.githubusercontent.com/87962465/175908588-3e319936-932d-4b51-9c22-5c5a3a00c8bf.png)

**Comment by Puvvl** [comment]
So there is no way to update the product price?

**Comment by nishekh-e-r** [comment]
@Puvvl  stripe doesn't support updating the price of an already created product with the price.

**Comment by Puvvl** [comment]
@nishekh-e-r I see, hm... In this case I think we can use `Pricing model` to manipulate with price, I know that you didn't implement yet. Do you have a plan to realize this future?
