### ISSUE TITLE
no plugin's collections ERROR

### ISSUE THREAD

**Issue by leszekkorzan** [manishkatyan/strapi-stripe#29]
I have installed strapi-stripe plugin, created poduct, make an order.
But there is an error connected with collections.

So there are no plugin's collections there.

![image](https://user-images.githubusercontent.com/42583915/178601230-8fe74545-03cb-4b4d-86c4-003e8815d43a.png)

in logs:
`error: select "t0".*, "t0"."id" from "strapi-stripe_strapi-stripe-product" as "t0" where ("t0"."id" = $1) limit $2 - invalid input syntax for type integer: "undefined"`

Errors also appear on handling (adding) order data

**Comment by leszekkorzan** [comment]
`  "dependencies": {
    "@strapi/plugin-users-permissions": "4.2.2",
    "@strapi/provider-email-nodemailer": "^4.2.2",
    "@strapi/strapi": "4.2.2",
    "@strapi/utils": "^4.2.2",
    "pg": "8.7.3",
    "pg-connection-string": "^2.5.0",
    "strapi-plugin-email-designer": "^2.1.1"
  },`

**Comment by leszekkorzan** [comment]
`insert into "strapi-stripe_strapi-stripe-payment" ("created_at", "customer_email", "customer_name", "is_txn_successful", "transaction_id", "txn_amount", "txn_date", "txn_message", "updated_at") values ($1, $2, $3, $4, $5, $6, $7, $8, $9) returning "id" - value too long for type character varying(255)
error: insert into "strapi-stripe_strapi-stripe-payment" ("created_at", "customer_email", "customer_name", "is_txn_successful", "transaction_id", "txn_amount", "txn_date", "txn_message", "updated_at") values ($1, $2, $3, $4, $5, $6, $7, $8, $9) returning "id" - value too long for type character varying(255)`

**Comment by nishekh-e-r** [comment]
@leszekkorzan 
you can see all the payment details in the strapi payment plugin dashboard, refer below screenshots.
![stripe-payment](https://user-images.githubusercontent.com/87962465/182055862-d2c2f4b2-0c59-4d38-ac5a-b632e9cdd150.png)
![stripe-payment-details2](https://user-images.githubusercontent.com/87962465/182055864-7f4d8d47-8708-4626-b6e3-7bad812d135a.png)
