### ISSUE TITLE
Docs clarification

### ISSUE THREAD

**Issue by telekosmos** [manishkatyan/strapi-stripe#30]
Hi, I've installed and used the plugin for Strapi 4.2.0 and playing around a bit but I couldn't figure out how to do, or if possible
- relate the products with any other content type (or viceversa)
- delete products (i.e. to prevent showing no longer available products)
- access to the products/payments using graphql
- at the docs I see _Add multiple “Buy Now” payment buttons on a page._ How this can be achieved? 

Thanks!

**Comment by nishekh-e-r** [comment]
- currently, the product doesn't support relation to another content type.
- we haven't included the option to delete, keeping in mind of the transaction already happened for the product in stripe. we will provide an archive option in future development.
- we will add graphql support in future releases.
- like the below` HTML demo code you can add multiple "Buy Now".

    <section class="mainsection">

        <div class="card" data-intro="Product card">
            <img src="https://cdn.pixabay.com/photo/2018/06/08/00/48/developer-3461405_960_720.png"
                alt="web Development" style="width:100%">
            <h1>Web Development</h1>
            <p class="price">&#8377;2,500</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
            <div><button type="button" class="SS_ProductCheckout" data-id="1" data-url="http://localhost:1337"> Buy Now
                </button></div>
        </div>
        <div class="card" data-intro="Product card">
            <img src="https://cdn.pixabay.com/photo/2018/06/08/00/48/developer-3461405_960_720.png"
                alt="web Development" style="width:100%" data-intro="Product Image" data-id="9">
            <h1>React Development</h1>
            <p class="price">&#8377;5,000</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
                dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
            <div><button type="button" class="SS_ProductCheckout" data-id="2" data-url="http://localhost:1337"> Buy Now
                </button></div>
        </div>
    </section>
