### ISSUE TITLE
Server wasn't able to start properly.

### ISSUE THREAD

**Issue by flashoop** [manishkatyan/strapi-stripe#31]
2022-07-30 08:50:21.968] debug: ⛔️ Server wasn't able to start properly.
[2022-07-30 08:50:21.969] error: The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

**Comment by brausend** [comment]
change node_modules/strapi-stripe/server/register.js
ln: 21
from
  const bbbJsPath = path.resolve(strapi.dirs.extensions, 'strapi-stripe', 'public', 'stripe.js');

to
  const bbbJsPath = path.resolve(strapi.dirs.dist.extensions, 'strapi-stripe', 'public', 'stripe.js');

does the trick.

**Comment by RanderGabriel** [comment]
I had the same problem here and the solution from @brausend  worked for me.

I am running it on windows. Has somebody faced this problem in other operational systems?

I can open a Pull Request changing it here, but it may need to be tested in other environments

**Comment by nishekh-e-r** [comment]
resolved
