### ISSUE TITLE
Contributing guidelines and roadmap

### ISSUE THREAD

**Issue by RanderGabriel** [manishkatyan/strapi-stripe#35]
I would like to help maintaining this project, but I don't know exactly what can I work on to help.

It would be really good if there was some roadmap for the next features or fixes that should be implemented. Is there any roadmap/backlog yet? If there is, in which tasks could I help?

Thank you for the good work on the library!

**Comment by nishekh-e-r** [comment]
Thanks, @RanderGabriel, for your offer to help maybe you can help in fixing errors/bugs going forward.
