### ISSUE TITLE
Question: How to view product API data in Strapi? Feature-Request?

### ISSUE THREAD

**Issue by oDinZu** [manishkatyan/strapi-stripe#36]
Strapi version: 4.1.11, 4.3.0
Strapi-Stripe Plugin version: 2.3.0

As an example, I goto https://api.example.com/api/posts?populate=* to populate all posts data.

I see I have a products collection with a product and that my api and stripe are connected and sharing data. 

when I goto: https://api.example.com/api/products I receive a 404.

when I view the roles and permissions for *public*, I don't have a *products* role to choose from like I do for "posts". 

In my collection, I also have the product collection and the products data for created product from the *payment* link on dashboard.

Furthermore, I create a new test collection type and it allows me to view it via as should, but with Stripe plugin, I am unable to view product data.

**Comment by oDinZu** [comment]
Update: 

I see if I goto: https://api.example.com/strapi-stripe/getProduct/2, I receive json data.

Am I able to retrieve all post data? 

preferably, I need to put all my product json data into one json file.

**Comment by nishekh-e-r** [comment]
@csharpee,  we will give api-endpoint to retrieve all the products.

**Comment by oDinZu** [comment]
also related to recent Strapi 4.3.0 update; i have had the same trouble with yalls plugin. https://forum.strapi.io/t/new-documentation-release-strapi-v4-3-0/20702/2

[quote="piwi, post:3, topic:20702"]
I’m not sure, but it looks like the error is related to the strapi-stripe plugin.
[/quote]
