### ISSUE TITLE
Feature-Request: Sync Product Data from Stripe if created on Stripe Dashboard

### ISSUE THREAD

**Issue by oDinZu** [manishkatyan/strapi-stripe#37]
Strapi version: 4.1.11, 4.3.0
Strapi-Stripe Plugin version: 2.3.0

When a user creates a product on Stripe dashboard, it should sync with the Strapi-Stripe.

Maybe a refresh or sync button in case the user decides to create a product on Stripe dashboard?

**Comment by oDinZu** [comment]
I ain't 100% sure what happened, but somehow I lost my Strapi stripe data after upgrading Strapi. On Stripe, my data is still there, but on Strapi it is no where to be found.

**Comment by nishekh-e-r** [comment]
@csharpee thanks for pointing out this issue, we will try to resolve it in the future release.
