### ISSUE TITLE
Feature-Request: Add Strapi Media Library button for product images.

### ISSUE THREAD

**Issue by oDinZu** [manishkatyan/strapi-stripe#38]
Strapi version: 4.1.11, 4.3.0
Strapi-Stripe Plugin version: 2.3.0

If I create a product in **Content-Manager**, it populates in products via payment link on dashboard as it should.

I want to change the following: 

The image box should open up Strapi Media library GUI to select an image, rather than manually copy / paste link. 

The copy / paste of absolute url works and allows for 3rd party CDN, but initially, the image by default should be Strapi Media Library.

![image](https://user-images.githubusercontent.com/18726788/182432203-d4cf5d79-55de-4183-aeff-b4e771d95829.png)

**Comment by oDinZu** [comment]
I am unable to edit the Product collection type. 

* Price is a drop down for some reason and doesn't work.
* Currency should be a drop down 
* Stripe productId and Stripeprice id should auto populate after product is created

![image](https://user-images.githubusercontent.com/18726788/182433046-fcb0620c-4882-4a22-a0b6-40933b0df41c.png)

**Comment by oDinZu** [comment]
As an example for a solution of the what the *Description* and Media Library *image* addition could look like, but keep the text entry for possible use of CDN.

![image](https://user-images.githubusercontent.com/18726788/182442230-5ab73f59-937a-4661-9b12-dfe17cce29c5.png)

**Comment by nishekh-e-r** [comment]
@csharpee  please install the latest version of strapi-stripe we have given feature to upload a file.
[link to package](https://www.npmjs.com/package/strapi-stripe)
