### ISSUE TITLE
Feature-Request: Make content-types editable; they are locked

### ISSUE THREAD

**Issue by oDinZu** [manishkatyan/strapi-stripe#39]
Strapi version: 4.1.11, 4.3.0
Strapi-Stripe Plugin version: 2.3.0

If I could edit the content-types, then I could update some things like the description to be *"Rich Text"* or *"Currency"* to be a drop-down.

Many of these fields should follow this: (I am unsure why Media type isn't populating the button) #38 

https://docs.strapi.io/user-docs/latest/content-manager/writing-content.html#filling-up-fields

![image](https://user-images.githubusercontent.com/18726788/182439937-a1ca0af3-675c-4ff2-95b2-60f6dae0412a.png)

**Comment by nishekh-e-r** [comment]
@csharpee we are not giving any option to edit content-type to prevent application crash or error, in the recent version we have hidden the product content-type.

![content](https://user-images.githubusercontent.com/87962465/182603315-247daf0d-67f9-4d38-8d46-80d867555921.png)
