### ISSUE TITLE
Feature-Request: Removing a product removes old product data on Stripe

### ISSUE THREAD

**Issue by oDinZu** [manishkatyan/strapi-stripe#41]
When you remove a product, remove it also from Stripe database.

Preferably, I would love to create all my products and manage them in Strapi only. Managing Strapi dashboard for posts and products, then managing Stripe products is lots of repetition.

**Comment by nishekh-e-r** [comment]
we haven't included the option to delete a product, keeping in mind of the transaction already happened for the product in stripe. we will provide an archive option in future development.
