### ISSUE TITLE
Image is not showing strapi-stripe checkout page and transaction report is not showing 

### ISSUE THREAD

**Issue by hamza-5570** [manishkatyan/strapi-stripe#45]
I have successfully linked stripe with strapi but on strapi checkout, the page image is not shown, and completing a successful transaction on test  mode the transaction is not shown on the transaction report.

**Comment by hamza-5570** [comment]
![Capture](https://user-images.githubusercontent.com/31978843/184820943-ab972b6e-27e9-42b5-9bd1-776b9ffe4ba0.JPG)

**Comment by nishekh-e-r** [comment]
@hamza-5570  are you running a project in development mode?
in that case strapi mediaLibrary store the images in the local database. stripe won't be able to fetch images from local.
once you configure your MediaLibrary to store data in amzon s3 or cloudinary, etc...
for more information check this out [https://strapi.io/features/media-library](url)
