### ISSUE TITLE
stripe error without key.

### ISSUE THREAD

**Issue by hotrungnhan** [manishkatyan/strapi-stripe#51]
![Screen Shot 2022-09-28 at 14 19 04](https://user-images.githubusercontent.com/40029631/192713896-72443885-16a4-4e39-b7dc-1c610d97077f.png)
strapi-stripe version : 2.5.1
@strapi/strapi : 4.3.8

**Comment by nishekh-e-r** [comment]
Hi @hotrungnhan,
we are checking on it. Will update you soon

**Comment by nishekh-e-r** [comment]
This error has been fixed in the latest version please check it out.
