### ISSUE TITLE
Invoke callback on purchase.

### ISSUE THREAD

**Issue by coconutbird** [manishkatyan/strapi-stripe#52]
Hi, I'd love the ability to invoke a server sided function on a callback to setup some records.  This plugin would be perfect if it could be used for SAAS subscriptions.

**Comment by nishekh-e-r** [comment]
Hi @coconutbird,
we are checking on it. Will update you soon.

**Comment by nishekh-e-r** [comment]
we have added a webhook URL section on the stripe configuration page.
please check out the latest version of the plugin, [here](https://www.npmjs.com/package/strapi-stripe)
