### ISSUE TITLE
Not a valid URL

### ISSUE THREAD

**Issue by itsmefarhan** [manishkatyan/strapi-stripe#53]
strapi version 4.4.5
strapi-stripe version 2.5.1

Payment type Subscription doesn't add product, in terminal it shows error "Not a valid URL". Payment type One-Time adds product successfully

**Comment by nishekh-e-r** [comment]
Hi @itsmefarhan 
we are checking on it. Will update you soon

**Comment by nishekh-e-r** [comment]
This issue has been fixed in the latest version please check it out.
