### ISSUE TITLE
Issue when using aws s3 upload provider

### ISSUE THREAD

**Issue by calvo-jp** [manishkatyan/strapi-stripe#60]
Hi. Is there a way I can configure the plugin to detect/respect my upload config? It currently appends the **http://localhost:1337** to the image url which stripe detects as an invalid url.

This is what it sends

<img width="349" alt="image" src="https://user-images.githubusercontent.com/86353187/204218851-a02f8c05-591b-41f2-96f2-b9296b8d0259.png">

And this is `stripe`'s response

<img width="341" alt="image" src="https://user-images.githubusercontent.com/86353187/204220182-cf5b555c-d830-4095-b806-4545cc4dbd15.png">

this is what I have in my `middleware.ts`

```js
{
 // more codes
 {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            "dl.airtable.com",
            "<bucket>.ap-southeast-1.amazonaws.com",
          ],
          "media-src": [
            "'self'",
            "data:",
            "blob:",
            "dl.airtable.com",
            "<bucket>.s3.ap-southeast-1.amazonaws.com",
          ],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
}
```

and on my `plugins.ts`

```ts
{
 // more codes
 upload: {
    config: {
      provider: "aws-s3",
      providerOptions: {
        accessKeyId: env("AWS_ACCESS_KEY_ID"),
        secretAccessKey: env("AWS_ACCESS_SECRET"),
        region: env("AWS_REGION"),
        params: {
          Bucket: env("AWS_BUCKET"),
        },
      },
      actionOptions: {
        upload: {},
        uploadStream: {},
        delete: {},
      },
    },
  },
}
```

Thanks in advance and really great work in here.

**Comment by nishekh-e-r** [comment]
Hi @calvo-jp 
we are checking on this issue, once it's done we will inform you.

**Comment by calvo-jp** [comment]
thank you @nishekh-e-r

**Comment by nishekh-e-r** [comment]
Hi @calvo-jp 
The image URL error has been fixed, please download the latest version package [here](https://www.npmjs.com/package/strapi-stripe)

**Comment by calvo-jp** [comment]
Omg. Thanks bro. I really appreciate it. Hope you guys all the best
