### ISSUE TITLE
parameter_invalid_integer - unit_amount, when rounding decimal prices

### ISSUE THREAD

**Issue by Robak08** [manishkatyan/strapi-stripe#67]
Hi,

stumbled upon this error in strapi logs. When creating product with decimal price (ex. 19.99), product is getting created but stripe cannot create price due to multiplication result.

Stripe dashboard log:
![image](https://user-images.githubusercontent.com/17516948/208943497-f268db0e-c803-4d74-a112-d1b20faa1588.png)

node ver. 14.17.4
strapi ver. 4.5.3
strapi-stripe ver. 3.1.0

**Comment by nishekh-e-r** [comment]
Hi @Robak08,
we have fixed the decimal point error while creating a product from the strapi, please download the latest version package [here](https://www.npmjs.com/package/strapi-stripe).

Thanks
