### ISSUE TITLE
Missing currency

### ISSUE THREAD

**Issue by Andi365** [manishkatyan/strapi-stripe#69]
Hi guys,

I cannot find the DKK - Danish krone option in the currency select field.

Should be found in the list under the letter D.
<img width="300" alt="currency" src="https://user-images.githubusercontent.com/43875035/212295108-8689af6f-055f-4102-b96c-d0a38dc3e786.png">

Thanks guys!

**Comment by nishekh-e-r** [comment]
Hi @Andi365 ,
we have added the Danish Krone currency, please download the new version of the plugin  [here](https://www.npmjs.com/package/strapi-stripe)
