### ISSUE TITLE
Recurring payments

### ISSUE THREAD

**Issue by XanderD99** [manishkatyan/strapi-stripe#7]
Not really an issue, more a question.

But is recurring payments supported with this plugin or is this something that is yet to be added.

If not added, would like to try an contribute to the project to have it implemented.

**Comment by manishkatyan** [comment]
Hi!

Thanks for your interest in Stripe Payments plugin. 

Recurring payment (subscription) is not added yet. We may add this feature if we get more interests from the plugin users. 

How would you want to contribute? Write to us at support@higheredlab.com to take the conversation forward.

**Comment by nishekh-e-r** [comment]
Hi!

Thanks for your interest in the Stripe Payments plugin.

Recurring payment (subscription) is not added yet. We may add this feature if we get more interest from the plugin users.

How would you want to contribute? Write to us at support@higheredlab.com to talk more.
