### ISSUE TITLE
If possible, switch to use Strapi MediaLib?

### ISSUE THREAD

**Issue by perostlin** [manishkatyan/strapi-stripe#70]
Would be nice if we could use Strapi MediaLib for products/subscriptions images, improves management and also includes use of other plugins like Cloudinary.

**Desired**
<img width="331" alt="image" src="https://user-images.githubusercontent.com/20464832/212634339-d37a38ea-f0ee-4c26-97a3-9cd079e287af.png">

**Current**
<img width="382" alt="image" src="https://user-images.githubusercontent.com/20464832/212634114-acce2aa6-71e0-4991-bd49-3383bd2a3d2f.png">

**Comment by nishekh-e-r** [comment]
@perostlin ,
We will try to implement this feature in a future release.
