### ISSUE TITLE
Query Subscription Products

### ISSUE THREAD

**Issue by nina-tehkar** [manishkatyan/strapi-stripe#72]
Please do correct me if I am wrong.

I don't see a method with the plugin APIs to poll the current status of any existing subscriptions for the user.

This makes the subscription integration far less useful as anyone using it will need to write custom APIs to get this status.

Less troublesome, but also would be great:
It also doesn't seem to associate the purchase with the current user, but rather with the email given to stripe.
It also doesn't pre-populate the stripe form with the current user's account email which would be convenient.

**Comment by nishekh-e-r** [comment]
Hi @nina-tehkar, 
we are working on these features, once its completed will let you know

**Comment by nishekh-e-r** [comment]
Hi @nina-tehkar the above features are implemented. you can update the package to the latest version from [here](https://www.npmjs.com/package/strapi-stripe)

![embed-email](https://user-images.githubusercontent.com/87962465/215028364-42aad2c1-3369-4c75-91c3-941ece410cf6.png)

![embed-subscription](https://user-images.githubusercontent.com/87962465/215028361-6cff9c49-9232-4e67-9862-1bdfa09e361c.png)
