### ISSUE TITLE
Guidance on active subscription for user

### ISSUE THREAD

**Issue by semics-tech** [manishkatyan/strapi-stripe#75]
I would like to know how you would ensure the user has an active subscription.

Do you store the stripe subscription id so that you can check the user has an active subscription?

I can't see anything obvious that I can use to access a user's subscription (like an id), any suggestions?

**Comment by nishekh-e-r** [comment]
@semics-tech 
In strapi-stripe v3.2.0 we have added a new API endpoint using which you can get an active subscription of a user.
![embedCode](https://user-images.githubusercontent.com/87962465/217756116-ebedd1cd-e12f-4067-af18-1321d3b33a8e.png)

subscription user email you can get easily in the payment report.
