### ISSUE TITLE
If possible, not to required Live Stripe Publishable Key and Live Stripe Secret Key?

### ISSUE THREAD

**Issue by djkenneth** [manishkatyan/strapi-stripe#77]
I would like to learn/upskill the strapi with stripe. I from philippines so it's hard to activate stripe from non US resident. Thank you

![Screenshot_3](https://user-images.githubusercontent.com/40983081/218374293-193fd862-fd82-463b-96fa-35b02e63ee09.png)

**Comment by nishekh-e-r** [comment]
@djkenneth 
if you don't want to enter the live stripe key you can enter the dummy credential, but make sure to enter valid live credentials if you are ready to enable live mode.
