### ISSUE TITLE
Ability to remove products

### ISSUE THREAD

**Issue by AlberGonAcosta** [manishkatyan/strapi-stripe#78]
Seems to be no manual way of removing an existing products in the plugin UI. You can remove the products from Stripe but not from Strapi. Currently, we are doing the removal manually in the database. There is an API call to remove a product from Stripe (https://stripe.com/docs/api/products/delete)

![image](https://user-images.githubusercontent.com/7900644/220122256-7676cbb6-fb2f-423d-97fa-3e2eef11bb3d.png)

**Comment by nishekh-e-r** [comment]
@AlberGonAcosta now you can delete products (note it will only delete products from the strapi database). please update to new version
