### ISSUE TITLE
Allow discount cupons with `allow_promotion_codes` parameter

### ISSUE THREAD

**Issue by fmercurio** [manishkatyan/strapi-stripe#80]
Hi,

We need to configure discounts cupons in our subscriptions by set the `allow_promotion_codes` parameter to `true`.

Any chances to allow it in the configuration panel in Strapi admins page?

See bellow the `allow_promotion_codes` in Stripe API documentation:

https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-allow_promotion_codes

**Comment by nishekh-e-r** [comment]
@fmercurio we added this feature please update the package to the latest version
