### ISSUE TITLE
Stripe API keys from .env

### ISSUE THREAD

**Issue by zhivkoangelov** [manishkatyan/strapi-stripe#84]
Hi,

Thanks for the great plugin. One disadvantage that I see is that Stripe API keys configuration is stored in the database along with all other settings. This makes it inconvenient to import-export settings between environments because API keys will be revealed in plain text. 
It would be great if API keys could be loaded (optionally) from .env variables. It's a minor change so I hope you will have it in mind.

Regards.

**Comment by nishekh-e-r** [comment]
@zhivkoangelov we are working on the issue will update you once we release new version.

**Comment by nishekh-e-r** [comment]
@zhivkoangelov We have removed the stripe secrets keys from the configuration, and now they are configured from .env variable.
To install the new version [strapi-stripe](https://www.npmjs.com/package/strapi-stripe).
Please try out the latest version and let us know what you think.
