### ISSUE TITLE
Missing featured: Cancel subscription

### ISSUE THREAD

**Issue by NicolasBrondin** [manishkatyan/strapi-stripe#86]
The plugin allows to create subscriptions, but there is no way to cancel the subscription through the plugin !

Also, thanks for this great plugin 🙏

**Comment by nishekh-e-r** [comment]
@NicolasBrondin, currently you can use the Stripe dashboard to manage your customer subscriptions, including cancellation and deletion. We are planning to introduce this feature in future releases. 
Thank you for bringing this to our attention, and we appreciate your patience as we work on implementing it.
