### ISSUE TITLE
Can't access to users & permissions settings after installing this plugin

### ISSUE THREAD

**Issue by ivan006** [manishkatyan/strapi-stripe#89]
### Required System information

- strapi-stripe": "^3.3.0",
- Node.js version:v18.16.0
- NPM version:9.5.1
- Strapi version:"@strapi/strapi": "^4.10.1",
- Database: mysql
- Operating system: win
- Is your project Javascript or Typescript: js

### Describe the bug

Whitescreen on admin/settings/users-permissions/roles after i install this plugin

### Steps to reproduce the behavior

1. Go to '[http://localhost:1337/admin/settings/users-permissions/roles](http://localhost:1337/admin/settings/users-permissions/roles)'
2. See whitescreen with error in console "The `request` function is deprecated and will be removed in the next major version. Please use `useFetchClient` instead."

### Expected behavior

Page loads

### Screenshots
![image](https://github.com/strapi/strapi/assets/17248313/9143a116-afd7-4abe-85fa-724e77cc564d)

**Comment by nishekh-e-r** [comment]
@ivan006 currently our plugin is compatible with the strapi version 4.5.3.
we are  working on the issues, once it's done will let you know

**Comment by nishekh-e-r** [comment]
Strapi recently upgrade the UI design system that includes several breaking changes. For example, Typescript was introduced, which is strongly typed. Another example is the upgraded Select component now has many more attributes. These breaking changes caused a few of the bugs that you all have been reporting. 

Good news! we have fixed those bugs. 

Please try out the latest version and let us know what you think. 
To install [strapi-stripe](https://www.npmjs.com/package/strapi-stripe)
