### ISSUE TITLE
Issue with entering a Product Description.

### ISSUE THREAD

**Issue by JonathanJKuhn** [manishkatyan/strapi-stripe#91]
After setting up the configuration with the API keys, I attempted to add a product. I could put all of the required information in, except for product description. For some reason, I am able to focus the field, but am unable to type a description. I can't submit a product while the description is empty.

I've reproduced this issue with a separate repo using the latest version of strapi and the plugin. Not sure if I'm missing something here.

**Comment by oliynykroman** [comment]
Have same issue :(

**Comment by hoangnhatfe** [comment]
Have same issue

**Comment by sachithraSP** [comment]
same here

**Comment by xqtm** [comment]
same here

**Comment by nishekh-e-r** [comment]
Hi there,
 The Strapi design system has been updated to the newer version. Our team is currently working on updating the Strapi-Stripe plugin to the latest version, and we will provide an update as soon as it's completed.

Thank you for your patience and understanding. If you have any more questions or concerns, please don't hesitate to let me know.

**Comment by canafran-sl** [comment]
Have same issue :(

**Comment by nishekh-e-r** [comment]
Strapi recently upgraded the UI design system which includes several breaking changes. For example, Typescript was introduced, which is strongly typed. Another example is the upgraded Select component now has many more attributes. These breaking changes caused a few of the bugs that you all have been reporting. 

Good news! we have fixed those bugs. 

Please try out the latest version and let us know what you think. 
[strapi-stripe](https://www.npmjs.com/package/strapi-stripe)
