### ISSUE TITLE
Issue trying to save plugin config

### ISSUE THREAD

**Issue by soyerno** [manishkatyan/strapi-stripe#98]
Hello, when I'm saving the configuration I got 403 error message from the endpoint strapi-stripe/getSettings.

Do you know how to solve it?. Thank you in advance.

![image](https://github.com/manishkatyan/strapi-stripe/assets/1170142/a4e07867-8a1a-4c11-8543-fbb257d13446)

**Comment by FlambeSk** [comment]
Hello, did you solved this problem? I am having same problem.

**Comment by FlavioScimeca** [comment]
same problem

**Comment by Amaan-Shaah** [comment]
Hi any one figured out a fix?

**Comment by FlavioScimeca** [comment]
> Hi any one figured out a fix?

I implemented the logic by my self

**Comment by FlambeSk** [comment]
> > Hi any one figured out a fix?
> 
> I implemented the logic by my self

Same, I implemented it by myself because it's still broken

**Comment by Amaan-Shaah** [comment]
> > > Hi any one figured out a fix?
> > 
> > 
> > I implemented the logic by my self
> 
> Same, I implemented it by myself because it's still broken

do you mean you added stripe outside of strapi?

**Comment by FlambeSk** [comment]
I have used Stripe node library and implemented API calls I needed
https://github.com/stripe/stripe-node

**Comment by FlavioScimeca** [comment]
> > > > Hi any one figured out a fix?
> > > 
> > > 
> > > I implemented the logic by my self
> > 
> > 
> > Same, I implemented it by myself because it's still broken
> 
> do you mean you added stripe outside of strapi?

Yes, take data from Strapi and than after payment change what you need in your Strapi  DB with Stripe Webhook
